import drools.vehicles.Emergency2
import drools.vehicles.Location
import drools.vehicles.Protocol

				// RULES FOR VEHICLE DISPLAY

rule "home"

    dialect "java"
    when
        u : Emergency2 (location.getPlace().equals("Home"))
    then 
        u.getLocation().setVehicle(Location.Vehicle.AMBULANCE);
end

rule "transit"

    dialect "java"
    when
        u : Emergency2 (location.getPlace().equals("Transit"))
    then 
        u.getLocation().setVehicle(Location.Vehicle.AMBULANCE);
end

rule "at work"

    dialect "java"
    when
        u : Emergency2 (location.getPlace().equals("Work place"))
    then 
        u.getLocation().setVehicle(Location.Vehicle.AMBULANCE);
end

rule "mountain"

    dialect "java"
    when
        u : Emergency2 (location.getPlace().equals("Mountain"))
    then 
        u.getLocation().setVehicle(Location.Vehicle.HELICOPTER);
end

rule "at the beach"

    dialect "java"
    when
        u : Emergency2 (location.getPlace().equals("Beach"))
    then 
        u.getLocation().setVehicle(Location.Vehicle.BOAT);
end

/*
  //-------> FURTHER CONSIDERATIONS FOR PROTOCOL DISPLAY   ----> I will take care of it

rule "is child"
	dialect "java"
	when
		u : Emergency2 (patient.getAge_range().equals("Child") && severity <= 3)
	then
		u.getLocation().setVehicle(Location.Vehicle.BOAT);
		System.out.println("I am here");
end

*/
/*
							// VEHICLE CONSIDERATIONS
rule "if advice"
	dialect "java"
	when
		u : Emergency2 (protocol.getProtocolType() == Protocol.Type.ADVICE)
	then
		u.getLocation().setVehicle(null);
end


*/

