import drools.symptoms.Emergency


							// CARDIOLOGY

rule "cardiology_heart_attack"
	dialect "java"
	when
		u: Emergency (specialty.equals("Cardiology") && specialty.getDisease_list().get(0).getDisease().equals("Heart attack"))
	then
		u.setSeverity(1);
		u.setProtocol(u.getProtocol_list().get(7));
end

rule "cardiology_heart_failure_severe"
	dialect "java"
	when
		u: Emergency (specialty.equals("Cardiology") && specialty.getDisease_list().get(1).getDisease().equals("Heart failure"))
	then
		u.setSeverity(3);
		u.setProtocol(u.getProtocol_list().get(8));
		
end

rule "cardiology_heart_failure_severe_light"
	dialect "java"
	when
		u: Emergency (specialty.equals("Cardiology") && specialty.getDisease_list().get(2).getDisease().equals("Heart failure"))
	then
		u.setSeverity(4);
		u.setProtocol(u.getProtocol_list().get(9));
		
end

rule "cardiology_hipertensive_crisis"
	dialect "java"
	when
		u: Emergency (specialty.equals("Cardiology") && specialty.getDisease_list().get(3).getDisease().equals("Hipertensive crisis"))
	then
		u.setSeverity(3);
		u.setProtocol(u.getProtocol_list().get(10));
		
end

rule "cardiology_ictus"
	dialect "java"
	when
		u: Emergency (specialty.equals("Cardiology") && specialty.getDisease_list().get(4).getDisease().equals("Ictus"))
	then
		u.setSeverity(1);
		u.setProtocol(u.getProtocol_list().get(11));
		
end

rule "cardiology_syncope_Ancients"
	dialect "java"
	when
		u: Emergency (specialty.equals("Cardiology") && specialty.getDisease_list().get(5).getDisease().equals("Syncope") && patient.getAge_range().equals("Ancient"))
	then
		u.setSeverity(4);
		u.setProtocol(u.getProtocol_list().get(12));
		
end


rule "cardiology_syncope_others"
	dialect "java"
	when
		u: Emergency (specialty.equals("Cardiology") && specialty.getDisease_list().get(6).getDisease().equals("Syncope"))
	then
		u.setSeverity(5);
		u.setProtocol(u.getProtocol_list().get(13));
		
end




							// TOXICOLOGY
							
rule "food_poisoning"
	dialect "java"
	when
		u: Emergency (specialty.equals("Toxicology") && specialty.getDisease_list().get(0).getDisease().equals("Food Poisoning"))
	then
		u.setSeverity(1);
		u.setProtocol(u.getProtocol_list().get(6));
		
end				
							

							// NEUROLOGY
rule "neurology_stroke"
	dialect "java"
	when
		u: Emergency (specialty.getDisease_list().get(0).getDisease().equals("Stroke"))
	then
		u.setSeverity(1);
		u.setProtocol(u.getProtocol_list().get(15));
		
end

rule "neurology_epilepsy_child"
	dialect "java"
	when
		u: Emergency (specialty.getDisease_list().get(1).getDisease().equals("Epilepsy"))
	then
		u.setSeverity(2);
		u.setProtocol(u.getProtocol_list().get(14));
		
end

rule "neurology_epilepsy_adult"
	dialect "java"
	when
		u: Emergency (specialty.getDisease_list().get(2).getDisease().equals("Epilepsy"))
	then
		u.setSeverity(3);
		u.setProtocol(u.getProtocol_list().get(14));
		
end

rule "neurology_epilepsy_elder"
	dialect "java"
	when
		u: Emergency (specialty.getDisease_list().get(2).getDisease().equals("Epilepsy"))
	then
		u.setSeverity(2);
		u.setProtocol(u.getProtocol_list().get(14));
		
end

rule "neurology_migraine_child"
	dialect "java"
	when
		u: Emergency (specialty.getDisease_list().get(3).getDisease().equals("Migraine"))
	then
		u.setSeverity(4);
		u.setProtocol(u.getProtocol_list().get(13));
		
end

rule "neurology_migraine_adult"
	dialect "java"
	when
		u: Emergency (specialty.getDisease_list().get(3).getDisease().equals("Migraine"))
	then
		u.setSeverity(5);
		u.setProtocol(u.getProtocol_list().get(13));
		
end

rule "neurology_migraine_elder"
	dialect "java"
	when
		u: Emergency (specialty.getDisease_list().get(3).getDisease().equals("Migraine"))
	then
		u.setSeverity(5);
		u.setProtocol(u.getProtocol_list().get(13));
		
end

rule "neurology_ptsd"
	dialect "java"
	when
		u: Emergency (specialty.getDisease_list().get(4).getDisease().equals("Ptsd"))
	then
		u.setSeverity(5);
		u.setProtocol(u.getProtocol_list().get(13));
		
end

rule "neurology_meningities"
	dialect "java"
	when
		u: Emergency (specialty.getDisease_list().get(3).getDisease().equals("Meningities"))
	then
		u.setSeverity(1);
		u.setProtocol(u.getProtocol_list().get(15));
		
end









							// TRAUMATOLOGY
							
							// ONCOLOGY
							
rule "oncology_colon_cancer_light"
	dialect "java"
	when
		u: Emergency (specialty.equals("Oncology") && specialty.getDisease_list().get(0).getDisease().equals("Colon cancer"))
	then
		u.setSeverity(4);
		u.setProtocol(u.getProtocol_list().get(4));
		
end

rule "oncology_colon_cancer_severe"
	dialect "java"
	when
		u: Emergency (specialty.equals("Oncology") &&  specialty.getDisease_list().get(1).getDisease().equals("Colon cancer"))
	then
		u.setSeverity(1);
		u.setProtocol(u.getProtocol_list().get(0));
end

rule "oncology_prostate_cancer_light"
	dialect "java"
	when
		u: Emergency (specialty.equals("Oncology") && specialty.getDisease_list().get(2).getDisease().equals("Prostate cancer"))
	then
		u.setSeverity(3);
		u.setProtocol(u.getProtocol_list().get(5));
end

rule "oncology_prostate_cancer_severe"
	dialect "java"
	when
		u: Emergency (specialty.equals("Oncology") && specialty.getDisease_list().get(3).getDisease().equals("Prostate cancer"))
	then
		u.setSeverity(2);
		u.setProtocol(u.getProtocol_list().get(0));
		System.out.println(u);
		
end


rule "oncology_lung_cancer_light"
	dialect "java"
	when
		u: Emergency (specialty.equals("Oncology") && specialty.getDisease_list().get(4).getDisease().equals("Lung cancer"))
	then
		u.setSeverity(3);
		u.setProtocol(u.getProtocol_list().get(1));
end

rule "oncology_lung_cancer_severe"
	dialect "java"
	when
		u: Emergency (specialty.equals("Oncology") && specialty.getDisease_list().get(5).getDisease().equals("Lung cancer"))
	then
		u.setSeverity(2);
		u.setProtocol(u.getProtocol_list().get(0));
end

rule "oncology_breast_cancer_light"
	dialect "java"
	when
		u: Emergency (specialty.equals("Oncology") && specialty.getDisease_list().get(6).getDisease().equals("Breast cancer"))
	then
		u.setSeverity(5);
		u.setProtocol(u.getProtocol_list().get(4));
end

rule "oncology_breast_cancer_severe"
	dialect "java"
	when
		u: Emergency (specialty.equals("Oncology") && specialty.getDisease_list().get(7).getDisease().equals("Breast cancer"))
	then
		u.setSeverity(1);
		u.setProtocol(u.getProtocol_list().get(0));
end

rule "oncology_leukemia_severe"
	dialect "java"
	when
		u: Emergency (specialty.equals("Oncology") && specialty.getDisease_list().get(8).getDisease().equals("Leukemia"))
	then
		u.setSeverity(1);
		u.setProtocol(u.getProtocol_list().get(3));
end

rule "oncology_leukemia_light"
	dialect "java"
	when
		u: Emergency (specialty.equals("Oncology") && specialty.getDisease_list().get(9).getDisease().equals("Leukemia"))
	then
		u.setSeverity(4);
		u.setProtocol(u.getProtocol_list().get(4));
end


							// OTHER

rule "other_unknown_light"
	dialect "java"
	when
		u: Emergency (specialty.equals("Other") && specialty.getDisease_list().get(0).getDisease().equals("Unknown (not urgent)"))
	then
		u.setSeverity(5);
		u.setProtocol(u.getProtocol_list().get(2));
end		

rule "other_unknown_severe"
	dialect "java"
	when
		u: Emergency (specialty.equals("Other") && specialty.getDisease_list().get(1).getDisease().equals("Unknown (urgent)"))
	then
		u.setSeverity(4);
		u.setProtocol(u.getProtocol_list().get(0));
end										



							