import drools.symptoms.Emergency


							// CARDIOLOGY

/*
rule "cardiology_heart_attack"
	dialect "java"
	when
		u: Emergency (specialty.equals("Cardiology") && specialty.getDisease_list().get(0).getDisease().equals("Heart attack"))
	then
		u.setSeverity(1);
		
	// ---> FALTA ESTE PROTOCOLO EN EXCEL --> TIENES Q PONER SU ÍNDICE (MIRA EN symptomsMain en cuál está metido)
		//u.setProtocol(u.getProtocol_list().get(4));
end

rule "cardiology_heart_failure"
	dialect "java"
	when
		u: Emergency (specialty.equals("Cardiology") && specialty.getDisease_list().get(1).getDisease().equals("Heart failure"))
	then
		u.setSeverity(2);
		
	// ---> FALTA ESTE PROTOCOLO EN EXCEL --> TIENES Q PONER SU ÍNDICE (MIRA EN symptomsMain en cuál está metido)
		//u.setProtocol(u.getProtocol_list().get(4));
end
*/

							// TOXICOLOGY
							
rule "food_poisoning"
	dialect "java"
	when
		u: Emergency (specialty.equals("Toxicology") && specialty.getDisease_list().get(0).getDisease().equals("Food Poisoning"))
	then
		u.setSeverity(1);
		u.setProtocol(u.getProtocol_list().get(6));
		
end				
							

							// NEUROLOGY

							// TRAUMATOLOGY
							
							// ONCOLOGY
							
rule "oncology_colon_cancer_light"
	dialect "java"
	when
		u: Emergency (specialty.equals("Oncology") && specialty.getDisease_list().get(0).getDisease().equals("Colon cancer"))
	then
		u.setSeverity(4);
		u.setProtocol(u.getProtocol_list().get(4));
		
end

rule "oncology_colon_cancer_severe"
	dialect "java"
	when
		u: Emergency (specialty.equals("Oncology") &&  specialty.getDisease_list().get(1).getDisease().equals("Colon cancer"))
	then
		u.setSeverity(1);
		u.setProtocol(u.getProtocol_list().get(0));
end

rule "oncology_prostate_cancer_light"
	dialect "java"
	when
		u: Emergency (specialty.equals("Oncology") && specialty.getDisease_list().get(2).getDisease().equals("Prostate cancer"))
	then
		u.setSeverity(3);
		u.setProtocol(u.getProtocol_list().get(5));
end

rule "oncology_prostate_cancer_severe"
	dialect "java"
	when
		u: Emergency (specialty.equals("Oncology") && specialty.getDisease_list().get(3).getDisease().equals("Prostate cancer"))
	then
		u.setSeverity(2);
		u.setProtocol(u.getProtocol_list().get(0));
		System.out.println(u);
		
end


rule "oncology_lung_cancer_light"
	dialect "java"
	when
		u: Emergency (specialty.equals("Oncology") && specialty.getDisease_list().get(4).getDisease().equals("Lung cancer"))
	then
		u.setSeverity(3);
		u.setProtocol(u.getProtocol_list().get(1));
end

rule "oncology_lung_cancer_severe"
	dialect "java"
	when
		u: Emergency (specialty.equals("Oncology") && specialty.getDisease_list().get(5).getDisease().equals("Lung cancer"))
	then
		u.setSeverity(2);
		u.setProtocol(u.getProtocol_list().get(0));
end

rule "oncology_breast_cancer_light"
	dialect "java"
	when
		u: Emergency (specialty.equals("Oncology") && specialty.getDisease_list().get(6).getDisease().equals("Breast cancer"))
	then
		u.setSeverity(5);
		u.setProtocol(u.getProtocol_list().get(4));
end

rule "oncology_breast_cancer_severe"
	dialect "java"
	when
		u: Emergency (specialty.equals("Oncology") && specialty.getDisease_list().get(7).getDisease().equals("Breast cancer"))
	then
		u.setSeverity(1);
		u.setProtocol(u.getProtocol_list().get(0));
end

rule "oncology_leukemia_severe"
	dialect "java"
	when
		u: Emergency (specialty.equals("Oncology") && specialty.getDisease_list().get(8).getDisease().equals("Leukemia"))
	then
		u.setSeverity(1);
		u.setProtocol(u.getProtocol_list().get(3));
end

rule "oncology_leukemia_light"
	dialect "java"
	when
		u: Emergency (specialty.equals("Oncology") && specialty.getDisease_list().get(9).getDisease().equals("Leukemia"))
	then
		u.setSeverity(4);
		u.setProtocol(u.getProtocol_list().get(4));
end


							// OTHER

rule "other_unknown_light"
	dialect "java"
	when
		u: Emergency (specialty.equals("Other") && specialty.getDisease_list().get(0).getDisease().equals("Unknown (not urgent)"))
	then
		u.setSeverity(5);
		u.setProtocol(u.getProtocol_list().get(2));
end		

rule "other_unknown_severe"
	dialect "java"
	when
		u: Emergency (specialty.equals("Other") && specialty.getDisease_list().get(1).getDisease().equals("Unknown (urgent)"))
	then
		u.setSeverity(4);
		u.setProtocol(u.getProtocol_list().get(0));
end										



							