
import pojos.Emergency;

							// OTHER 
							

rule "other_unknown_light"
	dialect "java"
	when
		u : Emergency (specialty.equals("Other") && specialty.getDisease_list().get(0).getDisease().equals("Unknown (not urgent)"))
	then
		u.setSeverity(5);
		u.setProtocol(u.getProtocol_list().get(2));
end		

rule "other_unknown_severe"
	dialect "java"
	when
		u : Emergency (specialty.equals("Other") && specialty.getDisease_list().get(1).getDisease().equals("Unknown (urgent)"))
	then
		u.setSeverity(4);
		u.setProtocol(u.getProtocol_list().get(0));
end										



							// ONCOLOGY
							
rule "oncology_colon_cancer_light"
	dialect "java"		
	when
		u : Emergency (specialty.equals("Oncology") && specialty.getDisease_list().get(0).getDisease().equals("Colon cancer"))
	then
		u.setSeverity(4);
		u.setProtocol(u.getProtocol_list().get(4));
		
end

rule "oncology_colon_cancer_severe"
	dialect "java"
	when
		u : Emergency (specialty.equals("Oncology") &&  specialty.getDisease_list().get(1).getDisease().equals("Colon cancer"))
	then
		u.setSeverity(1);
		u.setProtocol(u.getProtocol_list().get(0));
end

rule "oncology_prostate_cancer_light"
	dialect "java"
	when
		u : Emergency (specialty.equals("Oncology") && specialty.getDisease_list().get(2).getDisease().equals("Prostate cancer"))
	then
		u.setSeverity(3);
		u.setProtocol(u.getProtocol_list().get(5));
end

rule "oncology_prostate_cancer_severe"
	dialect "java"
	when
		u : Emergency (specialty.equals("Oncology") && specialty.getDisease_list().get(3).getDisease().equals("Prostate cancer"))
	then
		u.setSeverity(2);
		u.setProtocol(u.getProtocol_list().get(0));
		System.out.println(u);
		
end


rule "oncology_lung_cancer_light"
	dialect "java"
	when
		u : Emergency (specialty.equals("Oncology") && specialty.getDisease_list().get(4).getDisease().equals("Lung cancer"))
	then
		u.setSeverity(5);
		u.setProtocol(u.getProtocol_list().get(4));
end

rule "oncology_lung_cancer_severe"
	dialect "java"
	when
		u : Emergency (specialty.equals("Oncology") && specialty.getDisease_list().get(5).getDisease().equals("Lung cancer"))
	then
		u.setSeverity(1);
		u.setProtocol(u.getProtocol_list().get(15));
end

rule "oncology_breast_cancer_light"
	dialect "java"
	when
		u : Emergency (specialty.equals("Oncology") && specialty.getDisease_list().get(6).getDisease().equals("Breast cancer"))
	then
		u.setSeverity(5);
		u.setProtocol(u.getProtocol_list().get(4));
end

rule "oncology_breast_cancer_severe"
	dialect "java"
	when
		u : Emergency (specialty.equals("Oncology") && specialty.getDisease_list().get(7).getDisease().equals("Breast cancer"))
	then
		u.setSeverity(1);
		u.setProtocol(u.getProtocol_list().get(0));
end

rule "oncology_leukemia_severe"
	dialect "java"
	when
		u : Emergency (specialty.equals("Oncology") && specialty.getDisease_list().get(8).getDisease().equals("Leukemia"))
	then
		u.setSeverity(1);
		u.setProtocol(u.getProtocol_list().get(3));
end

rule "oncology_leukemia_light"
	dialect "java"
	when
		u : Emergency (specialty.equals("Oncology") && specialty.getDisease_list().get(9).getDisease().equals("Leukemia"))
	then
		u.setSeverity(4);
		u.setProtocol(u.getProtocol_list().get(4));
end



							// CARDIOLOGY
							

rule "cardiology_heart_attack"
	dialect "java"
	when
		u : Emergency (specialty.equals("Cardiology") && specialty.getDisease_list().get(0).getDisease().equals("Heart attack"))
	then
		u.setSeverity(1);
		u.setProtocol(u.getProtocol_list().get(18));
end

rule "cardiology_heart_failure_severe"
	dialect "java"
	when
		u : Emergency (specialty.equals("Cardiology") && specialty.getDisease_list().get(1).getDisease().equals("Heart failure"))
	then
		u.setSeverity(3);
		u.setProtocol(u.getProtocol_list().get(19));
		
end

rule "cardiology_heart_failure_severe_light"
	dialect "java"
	when
		u : Emergency (specialty.equals("Cardiology") && specialty.getDisease_list().get(2).getDisease().equals("Heart failure"))
	then
		u.setSeverity(4);
		u.setProtocol(u.getProtocol_list().get(20));
		
end

rule "cardiology_hipertensive_crisis"
	dialect "java"
	when
		u : Emergency (specialty.equals("Cardiology") && specialty.getDisease_list().get(3).getDisease().equals("Hipertensive crisis"))
	then
		u.setSeverity(3);
		u.setProtocol(u.getProtocol_list().get(21));
		
end

rule "cardiology_ictus"
	dialect "java"
	when
		u : Emergency (specialty.equals("Cardiology") && specialty.getDisease_list().get(4).getDisease().equals("Ictus"))
	then
		u.setSeverity(1);
		u.setProtocol(u.getProtocol_list().get(22));
		
end

rule "cardiology_syncope_Ancients"
	dialect "java"
	when
		u : Emergency (specialty.equals("Cardiology") && specialty.getDisease_list().get(5).getDisease().equals("Syncope") && patient.getAge_range().equals("Ancient"))
	then
		u.setSeverity(4);
		u.setProtocol(u.getProtocol_list().get(24));
		
end


rule "cardiology_syncope_others"
	dialect "java"
	when
		u : Emergency (specialty.equals("Cardiology") && specialty.getDisease_list().get(6).getDisease().equals("Syncope"))
	then
		u.setSeverity(5);
		u.setProtocol(u.getProtocol_list().get(23));
		
end




							// TOXICOLOGY
							
rule "toxycology_food_poisoning"

	dialect "java"

	when

		u : Emergency (specialty.equals("Toxicology") && specialty.getDisease_list().get(0).getDisease().equals("Food poisoning"))

	then

		u.setSeverity(3);
		u.setProtocol(u.getProtocol_list().get(6));

end


rule "drugs_cronical"

	dialect "java"

	when

		u : Emergency (specialty.equals("Toxicology") && specialty.getDisease_list().get(1).getDisease().equals("Drugs"))

	then

		u.setSeverity(2);
		u.setProtocol(u.getProtocol_list().get(6));

end


rule "hangover"

	dialect "java"

	when

		u : Emergency (specialty.equals("Toxicology") && specialty.getDisease_list().get(2).getDisease().equals("Hangover"))

	then

		u.setSeverity(4);
		u.setProtocol(u.getProtocol_list().get(6));

end


rule "medicament_allergy"

	dialect "java"

	when

		u : Emergency (specialty.equals("Toxicology") && specialty.getDisease_list().get(3).getDisease().equals("Medicament allergy"))

	then

		u.setSeverity(1);
		u.setProtocol(u.getProtocol_list().get(6));

end


		
							

							// NEUROLOGY
rule "neurology_stroke"
	dialect "java"
	when
		u : Emergency (specialty.equals("Neurology") && specialty.getDisease_list().get(0).getDisease().equals("Stroke"))
	then
		u.setSeverity(1);
		u.setProtocol(u.getProtocol_list().get(15));
		
end

rule "neurology_epilepsy"
	dialect "java"
	when
		u : Emergency (specialty.equals("Neurology") && specialty.getDisease_list().get(1).getDisease().equals("Epilepsy"))
	then
		u.setSeverity(2);
		u.setProtocol(u.getProtocol_list().get(14));
		
end


rule "neurology_migraine"
	dialect "java"
	when
		u : Emergency (specialty.equals("Neurology") && specialty.getDisease_list().get(2).getDisease().equals("Migraine"))
	then
		u.setSeverity(4);
		u.setProtocol(u.getProtocol_list().get(13));
		
end




rule "neurology_ptsd"
	dialect "java"
	when
		u : Emergency (specialty.equals("Neurology") && specialty.getDisease_list().get(3).getDisease().equals("Ptsd"))
	then
		u.setSeverity(5);
		u.setProtocol(u.getProtocol_list().get(13));
		
end

rule "neurology_meningities"
	dialect "java"
	when
		u : Emergency (specialty.equals("Neurology") && specialty.getDisease_list().get(4).getDisease().equals("Meningities"))
	then
		u.setSeverity(1);
		u.setProtocol(u.getProtocol_list().get(15));
		
end


							// TRAUMATOLOGY
							

rule "First Degree Burn"
	dialect "java"
	when
		u : Emergency (specialty.equals("Traumatology") && specialty.getDisease_list().get(0).getDisease().equals("First Degree Burn"))
	then
		u.setSeverity(5);
		u.setProtocol(u.getProtocol_list().get(25));
end

rule "Second Degree Burn"
	dialect "java"
	when
		u : Emergency (specialty.equals("Traumatology") && specialty.getDisease_list().get(1).getDisease().equals("Second Degree Burn"))
	then
		u.setSeverity(3);
		u.setProtocol(u.getProtocol_list().get(9));

end

rule "Third Degree Burn"
	dialect "java"
	when
		u : Emergency (specialty.equals("Traumatology") && specialty.getDisease_list().get(2).getDisease().equals("Third Degree Burn"))
	then
		u.setSeverity(1);
		u.setProtocol(u.getProtocol_list().get(9));

end

rule "Acute Dislocation"
	dialect "java"
	when
		u : Emergency (specialty.equals("Traumatology") && specialty.getDisease_list().get(3).getDisease().equals("Acute Dislocation "))
	then
		u.setSeverity(3);
		u.setProtocol(u.getProtocol_list().get(17));

end

rule "Chronic Dislocation"
	dialect "java"
	when
		u : Emergency (specialty.equals("Traumatology") && specialty.getDisease_list().get(4).getDisease().equals("Chronic Dislocation"))
	then
		u.setSeverity(4);
		u.setProtocol(u.getProtocol_list().get(26));

end

rule "First Degree Sprain "
	dialect "java"
	when
		u : Emergency (specialty.equals("Traumatology") && specialty.getDisease_list().get(5).getDisease().equals("First Degree Sprain ")
	then
		u.setSeverity(2);
		u.setProtocol(u.getProtocol_list().get(27));

end

rule "Second Degree Sprain"
	dialect "java"
	when
		u : Emergency (specialty.equals("Traumatology") && specialty.getDisease_list().get(6).getDisease().equals("Second Degree Sprain"))
	then
		u.setSeverity(2);
		u.setProtocol(u.getProtocol_list().get(28));

end

rule "Third Degree Sprain"
	dialect "java"
	when
		u : Emergency (specialty.equals("Traumatology") && specialty.getDisease_list().get(7).getDisease().equals("Third Degree Sprain"))
	then
		u.setSeverity(1);
		u.setProtocol(u.getProtocol_list().get(28));
end

rule "Complete Fracture"
	dialect "java"
	when
		u : Emergency (specialty.equals("Traumatology") && specialty.getDisease_list().get(8).getDisease().equals("Complete Fracture"))
	then
		u.setSeverity(1);
		u.setProtocol(u.getProtocol_list().get(28));

end

rule "Green Stem Fracture"
	dialect "java"
	when
		u : Emergency (specialty.equals("Traumatology") && specialty.getDisease_list().get(9).getDisease().equals("Green Stem Fracture"))
	then
		u.setSeverity(2);
		u.setProtocol(u.getProtocol_list().get(29));

end

rule "Comminuted Fracture"
	dialect "java"
	when
		u : Emergency (specialty.equals("Traumatology") && specialty.getDisease_list().get(10).getDisease().equals("Comminuted Fracture"))
	then
		u.setSeverity(1);
		u.setProtocol(u.getProtocol_list().get(28));

end

rule "Open Fracture"
	dialect "java"
	when
		u : Emergency (specialty.equals("Traumatology") && specialty.getDisease_list().get(11).getDisease().equals("Open Fracture"))
	then
		u.setSeverity(1);
		u.setProtocol(u.getProtocol_list().get(28));

end

rule "Mild Head Trauma"
	dialect "java"
	when
		u : Emergency (specialty.equals("Traumatology") && specialty.getDisease_list().get(12).getDisease().equals("Mild Head Trauma")
	then
		u.setSeverity(2);
		u.setProtocol(u.getProtocol_list().get(30));

end

rule "Complete Spinal Cord Injury"
	dialect "java"
	when
		u : Emergency (specialty.equals("Traumatology") && specialty.getDisease_list().get(13).getDisease().equals("Complete Spinal Cord Injury"))
	then
		u.setSeverity(1);
		u.setProtocol(u.getProtocol_list().get(31));

end

rule "Internal Bleeding"
	dialect "java"
	when
		u : Emergency (specialty.equals("Traumatology") && specialty.getDisease_list().get(14).getDisease().equals("Internal Bleeding"))
	then
		u.setSeverity(1);
		u.setProtocol(u.getProtocol_list().get(31));

end

rule "External Bleeding"
	dialect "java"
	when
		u : Emergency (specialty.equals("Traumatology") && specialty.getDisease_list().get(15).getDisease().equals("External Bleeding")
	then
		u.setSeverity(1);
		u.setProtocol(u.getProtocol_list().get(32));

end

rule "Venous Hemorrhage"
	dialect "java"
	when
		u : Emergency (specialty.equals("Traumatology") && specialty.getDisease_list().get(16).getDisease().equals("Venous Hemorrhage"))
	then
		u.setSeverity(2);
		u.setProtocol(u.getProtocol_list().get(33));

end

rule "Arterial Bleeding"
	dialect "java"
	when
		u : Emergency (specialty.equals("Traumatology") && specialty.getDisease_list().get(17).getDisease().equals("Arterial Bleeding"))
	then
		u.setSeverity(1);
		u.setProtocol(u.getProtocol_list().get(33));

end
							
							
							
							
							
							
							
							
							
							
							
							
							
							
							
							
							
							
							
							
							
							


							